import day1, day2, day3, day4, day5, day6, day7, day8, day9, day10

if __name__ == '__main__':
    print(f"Day 1a: {day1.find_solution_a()}")
    print(f"Day 1b: {day1.find_solution_b()}")
    print(f"Day 2a: {day2.find_solution_a()}")
    print(f"Day 2b: {day2.find_solution_b()}")
    print(f"Day 3a: {day3.find_solution_a()}")
    print(f"Day 3b: {day3.find_solution_b()}")
    print(f"Day 4a: {day4.find_solution_a()}")
    print(f"Day 4b: {day4.find_solution_b()}")
    print(f"Day 5a: {day5.find_solution_a()}")
    print(f"Day 5b: {day5.find_solution_b()}")
    print(f"Day 6a: {day6.find_solution_a()}")
    print(f"Day 6b: {day6.find_solution_b()}")
    print(f"Day 7a: {day7.find_solution_a()}")
    print(f"Day 7b: {day7.find_solution_b()}")
    print(f"Day 8a: {day8.find_solution_a()}")
    print(f"Day 8b: {day8.find_solution_b()}")
    print(f"Day 9a: {day9.find_solution_a()}")
    print(f"Day 9b: {day9.find_solution_b()}")
    print(f"Day 10a: {day10.find_solution_a()}")
    print(f"Day 10b: {day10.find_solution_b()}")